
package com.neusoft.mid.ec.api.service.civiladministration.BookTime;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookTimeServicePortType", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookTimeServicePortType {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/")
    @RequestWrapper(localName = "getBookTime", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/", className = "com.neusoft.mid.ec.api.service.civiladministration.BookTime.GetBookTime")
    @ResponseWrapper(localName = "getBookTimeResponse", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/", className = "com.neusoft.mid.ec.api.service.civiladministration.BookTime.GetBookTimeResponse")
    public String getBookTime(
        @WebParam(name = "arg0", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/")
        String arg2);

}
