
package com.neusoft.mid.ec.api.service.civiladministration.BookTime;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookTimeService", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/", wsdlLocation = "http://59.207.24.170:8099/marry_book/ws/getBookTime?wsdl")
public class BookTimeService
    extends Service
{

    private final static URL BOOKTIMESERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKTIMESERVICE_EXCEPTION;
    private final static QName BOOKTIMESERVICE_QNAME = new QName("http://service.ws.gUnit_marry_mzb.topsuntech.com/", "BookTimeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://59.207.24.170:8099/marry_book/ws/getBookTime?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKTIMESERVICE_WSDL_LOCATION = url;
        BOOKTIMESERVICE_EXCEPTION = e;
    }

    public BookTimeService() {
        super(__getWsdlLocation(), BOOKTIMESERVICE_QNAME);
    }

    public BookTimeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKTIMESERVICE_QNAME, features);
    }

    public BookTimeService(URL wsdlLocation) {
        super(wsdlLocation, BOOKTIMESERVICE_QNAME);
    }

    public BookTimeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKTIMESERVICE_QNAME, features);
    }

    public BookTimeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookTimeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookTimeServicePortType
     */
    @WebEndpoint(name = "BookTimeServicePort")
    public BookTimeServicePortType getBookTimeServicePort() {
        return super.getPort(new QName("http://service.ws.gUnit_marry_mzb.topsuntech.com/", "BookTimeServicePort"), BookTimeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookTimeServicePortType
     */
    @WebEndpoint(name = "BookTimeServicePort")
    public BookTimeServicePortType getBookTimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.gUnit_marry_mzb.topsuntech.com/", "BookTimeServicePort"), BookTimeServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKTIMESERVICE_EXCEPTION!= null) {
            throw BOOKTIMESERVICE_EXCEPTION;
        }
        return BOOKTIMESERVICE_WSDL_LOCATION;
    }

}
