
package com.neusoft.mid.ec.api.service.civiladministration.BookDept;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookDeptService", targetNamespace = "http://service.ws.gUnit_marry_mzb.topsuntech.com/", wsdlLocation = "http://59.207.24.170:8099/marry_book/ws/getDeptInfo?wsdl")
public class BookDeptService
    extends Service
{

    private final static URL BOOKDEPTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKDEPTSERVICE_EXCEPTION;
    private final static QName BOOKDEPTSERVICE_QNAME = new QName("http://service.ws.gUnit_marry_mzb.topsuntech.com/", "BookDeptService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://59.207.24.170:8099/marry_book/ws/getDeptInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKDEPTSERVICE_WSDL_LOCATION = url;
        BOOKDEPTSERVICE_EXCEPTION = e;
    }

    public BookDeptService() {
        super(__getWsdlLocation(), BOOKDEPTSERVICE_QNAME);
    }

    public BookDeptService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKDEPTSERVICE_QNAME, features);
    }

    public BookDeptService(URL wsdlLocation) {
        super(wsdlLocation, BOOKDEPTSERVICE_QNAME);
    }

    public BookDeptService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKDEPTSERVICE_QNAME, features);
    }

    public BookDeptService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookDeptService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookDeptServicePortType
     */
    @WebEndpoint(name = "BookDeptServicePort")
    public BookDeptServicePortType getBookDeptServicePort() {
        return super.getPort(new QName("http://service.ws.gUnit_marry_mzb.topsuntech.com/", "BookDeptServicePort"), BookDeptServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookDeptServicePortType
     */
    @WebEndpoint(name = "BookDeptServicePort")
    public BookDeptServicePortType getBookDeptServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.gUnit_marry_mzb.topsuntech.com/", "BookDeptServicePort"), BookDeptServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKDEPTSERVICE_EXCEPTION!= null) {
            throw BOOKDEPTSERVICE_EXCEPTION;
        }
        return BOOKDEPTSERVICE_WSDL_LOCATION;
    }

}
