server:
  port: 9668
  servlet:
    context-path: /backsys
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    #本地测试环境
    url: jdbc:mysql://localhost:3306/yushiban?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: 12358
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dr.backsys.entity
#  config-location: classpath:/mybatis-config.xml